server:
  port: 8082

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_transaction_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  kafka:
    enabled: false
  redis:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
